openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /api/pong:
    get:
      operationId: pong
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
      tags:
      - ping-controller
      x-accepts: application/json
  /api/ping:
    get:
      operationId: ping
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
      tags:
      - ping-controller
      x-accepts: application/json
components:
  schemas: {}

